---
- hosts: localhost

  tasks:
    - name: Retrieve SSH Private Key for Login from CyberArk
      cyberark_credential:
        api_base_url: "https://pvwa.192.168.3.102.xip.io"
        validate_certs: no
        client_cert: ""
        client_key: "" 
        app_id: "Ansible"
        query: "Safe=D-LIN-ROOT-SSHKEYS;Folder=Root;Object=ANSIBLE-RHEL01-KEY"
      register: cyberark_key_response
      delegate_to: localhost
      no_log: no

    - name: Retrieve REST API Service Account for Onboarding to CyberArk
      cyberark_credential:
        api_base_url: "https://pvwa.192.168.3.102.xip.io"
        validate_certs: no
        client_cert: ""
        client_key: "" 
        app_id: "Ansible"
        query: "Safe=D-CYBR-RESTAPI-ACCTS;Folder=Root;Object=ANSIBLE-RESTAPI-USER"
      register: cyberark_user_response
      delegate_to: localhost
      no_log: yes

    - name: Initiate TempFile Module for SSH Private Key
      tempfile:
        state: file
        suffix: key
      register: temp_key
      no_log: yes

    - name: Write SSH Private Key to TempFile
      copy:
        dest: "{{ temp_key.path }}"
        content: "{{ cyberark_key_response.result.Content }}"
      delegate_to: localhost
      changed_when: false
      no_log: yes
      
    - name: Set SSH Private Key TempFile to Fact Named cyberark_ssh_privatekey
      set_fact:
        cyberark_ssh_privatekey: "{{ temp_key.path }}"
      no_log: yes

    - name: Set REST API Username to Fact Named cyberark_secret_username
      set_fact:
        cyberark_secret_username: "{{ cyberark_user_response.result.UserName }}"
      no_log: yes
    
    - name: Set REST API User Password to Fact Named cyberark_secret_userpass
      set_fact:
        cyberark_secret_userpass: "{{ cyberark_user_response.result.Content }}"
      no_log: yes

- hosts: all
  gather_facts: yes
  vars:
    ansible_ssh_user: "root"
    ansible_ssh_private_key_file: "{{ hostvars['localhost']['cyberark_ssh_privatekey'] }}"
    cyberark_rest_user: "{{ hostvars['localhost']['cyberark_secret_username'] }}"
    cyberark_rest_pass: "{{ hostvars['localhost']['cyberark_secret_userpass'] }}"
    mysql_username: "demo"

  roles:
    - cyberark.modules

  tasks:
    - name: Install Apache & PHP
      yum:
        name: "{{ item }}"
        state: present
      with_items:
          - httpd
          - php
          - php-mysql

    - name: Install Web Role Specific Dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
          - git
          - wget
          - curl
          - jq
          - libsemanage-python

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Configure SELinux to Allow httpd Connection to Remote Database
      seboolean:
        name: httpd_can_network_connect_db
        state: true
        persistent: yes

    - name: Create index.php Start Page
      copy:
        dest: "/var/www/html/index.php"
        content: |
          <?php echo "Hello World!"; ?>

    - name: Install MariaDB Package
      yum:
        name: "{{ item }}"
        state: present
      with_items:
          - mariadb-server
          - MySQL-python

    - name: Configure SELinux to Start MySQL on Any Port 
      seboolean:
        name: mysql_connect_any
        state: true
        persistent: yes

    - name: Start MySQL Service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a New Database
      mysql_db:
        name: demo
        state: present
        collation: utf8_general_ci

    - name: Set Fact with Randomized Password for MySQL Database User
      set_fact:
        mysql_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
      no_log: yes

    - name: Create a Database User
      mysql_user:
        name: "{{ mysql_username }}"
        password: "{{ mysql_password }}"
        priv: "*.*:ALL"
        host: localhost
        state: present

    - name: Authenticate to CyberArk Web Services
      cyberark_authentication:
        api_base_url: "https://pvwa.192.168.3.102.xip.io"
        validate_certs: no
        username: "{{ cyberark_rest_user }}"
        password: "{{ cyberark_rest_pass }}"

    - name: Set CyberArk Authn Token to Fact Named cyberark_authn_token
      set_fact:
        cyberark_authn_token: "{{ cyberark_session.token }}"
      no_log: yes

    - name: Onboard MySQL Local User to CyberArk EPV
      uri:
        url: https://pvwa.192.168.3.102.xip.io/PasswordVault/api/Accounts/
        headers:
          Content-Type: application/json
          Authorization: "{{ cyberark_authn_token }}"
        method: POST 
        status_code: 201
        body:
          name: "MYSQL-DEMO-USER"
          address: "rhel01.192.168.3.104.xip.io"
          userName: "{{ mysql_username }}"
          platformId: "MySQL"
          safeName: "D-MYSQL-LOCAL-USERS"
          secretType: "password"
          secret: "{{ mysql_password }}"
          secretManagement:
            automaticManagementEnabled: yes
        body_format: json
        validate_certs: no

    - name: Logoff from CyberArk Web Services
      cyberark_authentication:
        state: absent 
        cyberark_session: "{{ cyberark_session }}"

    - name: Copy sample data to local filesystem /tmp/
      copy:
        src: files/dump.sql
        dest: /tmp/dump.sql
    
    - name: Insert sample data into demo table in MySQL
      shell: "mysql -u {{ mysql_username }} -p{{ mysql_password }} demo < /tmp/dump.sql"

    - name: Restart Apache 
      service:
        name: httpd
        state: restarted

    - name: Install Database Connection PHP Script db.php
      copy:
        src: files/db.php
        dest: /var/www/html/db.php
