name: ssb-pub
image: debian-9-x64
min_size: 1gb
config:
  #cloud-config
  packages:
    - wget
  runcmd:
    - wget https://raw.githubusercontent.com/ahdinosaur/ssb-pub/master/install.sh
    - bash install.sh
