#!/usr/bin/env bash
set -e
wget "https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb"
dpkg -i puppetlabs-release-pc1-trusty.deb
apt-get update
apt-get install -y puppet git ruby
gem install r10k
