# This playbook install all packages for the FedoraFSL Security Lab.
#
# Copyright (c) 2013-2019 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved. 
#
# Synced at 2018-08-12
#
---
- hosts: fsl_hosts
  user: root
  tasks:
  - name: install $item
    dnf: pkg=$item state=installed
    with_items:
       - ArpON
       - afftools
       - aide
       - aircrack-ng
       - airsnort
       - argus
       - argus-clients
       - arp-scan
       - bannergrab
       - binwalk
       - bkhive
       - bmon
       - bonesi
       - bro
       - captcp
       - chkrootkit
       - ciphertest
       - cmospwd
       - cowpatty
       - dc3dd
       - dcfldd
       - ddrescue
       - dhcping
       - dislocker
       - dnsenum
       - dnsmap
       - dnstop
       - dnstracer
       - driftnet
       - dsniff
       - dstat
       - echoping
       - etherape
       - ettercap
       - ewftools
       - examiner
       - extundelete
       - firewalk
       - firstaidkit-gui
       - firstaidkit-plugin-all
       - flawfinder
       - foremost
       - fpdns
       - fping
       - goaccess
       - gparted
       - halberd
       - hans
       - hexedit
       - hfsutils
       - horst
       - hping3
       - ht
       - htop
       - httpd-tools
       - httpie
       - httping
       - httpress
       - httpry
       - httrack
       - hunt
       - hydra
       - iftop
       - ike-scan
       - inception
       - inxi
       - iperf
       - iptraf-ng
       - irssi
       - john
       - kismet
       - kismon
       - labrea
       - lbd
       - lnav
       - lynis
       - macchanger
       - masscan
       - mausezahn
       - mc
       - mcabber
       - medusa
       - mtr
       - mutt
       - nano
       - nbtscan
       - nc
       - nc6
       - ncrack
       - nebula
       - net-snmp
       - net-snmp-utils
       - netactview
       - netdisco
       - nethogs
       - netsed
       - netsniff-ng
       - nfspy
       - nfswatch
       - ngrep
       - nicstat
       - nikto
       - nload
       - nmap
       - nmap-frontend
       - nmbscan
       - ntfs-3g
       - ntfsprogs
       - ntop
       - ntp
       - nwipe
       - onesixtyone
       - openssh
       - openvas-cli
       - openvas-gsa
       - openvas-scanner
       - ophcrack
       - p0f
       - packETH
       - pads
       - paris-traceroute
       - pcapdiff
       - pcapfix
       - pdfcrack
       - picviz-gui
       - powertop
       - proxychains-ng
       - psad
       - pscan
       - pwgen
       - pyrit
       - raddump
       - ratproxy
       - rats
       - reaver
       - rkhunter
       - safecopy
       - samdump2
       - scalpel
       - scamper
       - scanmem
       - scap-security-guide
       - scap-workbench
       - scapy
       - screen
       - scrub
       - sectool-gui
       - security-menus
       - setools-gui
       - siege
       - sing
       - sipp
       - sipsak
       - skipfish
       - sleuthkit
       - slowhttptest
       - snmpcheck
       - socat
       - sockperf
       - splint
       - sqlninja
       - srm
       - sshscan
       - ssldump
       - sslscan
       - sslsplit
       - sslstrip
       - subnetcalc
       - sucrack
       - swaks
       - sysstat
       - sysstat
       - tcpcrypt
       - tcpdump
       - tcpflow
       - tcpick
       - tcpjunk
       - tcpreen
       - tcpreplay
       - tcptrack
       - tcpxtract
       - telnet
       - testdisk
       - testssl
       - thc-ipv6
       - tlssled
       - trafshow
       - tripwire
       - unhide
       - unicornscan
       - uperf
       - usbsniff
       - vim-enhanced
       - vnstat
       - wavemon
       - wbox
       - weplab
       - wget
       - whois
       - wipe
       - wireshark
       - wireshark-gtk
       - yersinia
       - yum-utils
       - zmap
