name: LineageOS-z3s

on:
    workflow_dispatch: 

jobs:
    build:
      runs-on: ubuntu-22.04
      steps:
      - name: Free disk space (1/3)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/3)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (3/3)
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'
          
      - name: Install the build packages
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
      
      - name: Create the directories
        run: |
          mkdir -p ~/bin
          mkdir -p ~/android/lineage
      
      - name: Install the repo command
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          sudo cp ~/bin/repo /usr/bin/repo
          sudo chmod a+x ~/bin/repo
          sudo chmod a+x /usr/bin/repo

      - name: Configure git
        run: |
          git config --global user.email romartisan2025@gmail.com
          git config --global user.name Artisan
      
      - name: Initialize the LineageOS source repository
        run: |
          cd ~/android/lineage
          repo init -u https://github.com/ArtisanROM/android.git -b lineage-21.0 --git-lfs
          repo sync

      - name: Prepare the device-specific code
        run: |
          cd ~/android/lineage
          mkdir .repo/local_manifests
          curl -o .repo/local_manifests/roomservice.xml https://raw.githubusercontent.com/Android-Artisan/LineageOS/refs/heads/main/manifest/s20x/roomservice.xml
          source build/envsetup.sh
      
      - name: Start the build
        run: |
          cd ~/android/lineage
          source build/envsetup.sh
          brunch z3s

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ~/android/lineage/$OUT/recovery.img
          name: lineageos-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: lineageos 21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
              ~/android/lineage/$OUT/lineage-21.0-*-UNOFFICIAL-z3s.zip
          name: lineageos-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: lineageos 21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
